events_api_mysql:
  name: events_api_mysql
  container_name: events_api_mysql
  build: docker/mysql
  volumes:
    - /var/lib/mysql:/var/lib/mysql

events_api_tomcat:
  name: events_api_tomcat
  container_name: events_api_tomcat
  build: docker/tomcat
  ports:
   - "9090:8080"
  links:
   - events_api_mysql

